name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      # 1. 기존 Docker 컨테이너 삭제
      - name: Delete Docker Image and Containers
        run: |
          sudo docker rm -f dweb || true

      # 2. Docker Hub에서 최신 이미지 풀
      - name: Pull Docker Image from Docker Hub
        run: sudo docker pull dweblab/songdo:latest

      # 3. Docker 컨테이너 실행
      - name: Execute Docker Container
        run: sudo docker run -d -p 80:3000 --name dweb dweblab/songdo:latest
